# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea8c9820a0e0dcae4a9607387eaedf9250b908e4d34794496348c08023081ff8c8680bf433e3f3782fb37a06f613d73c5108c36c7a5120cb63323ebf5eba2695

test:
  secret_key_base: 3f996b6d81b4759a19976413fda73cf342517d6a4b8d7ee80a0eb38ba17037062e254c88168ee328b7e7342153c16d2eee2beabd1478ed5b48bcd2e6f8ffa482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
